### ISSUE TITLE
Issue while pip installing fft package

### ISSUE THREAD

**Issue by Mrmoore98** [BaoWangMath/LaplacianSmoothing-GradientDescent#1]
I can't install this package in win 10`(base) C:\Users\dell>pip install C:\Users\dell\Downloads\pytorch_fft-0.15.tar.gz
Processing c:\users\dell\downloads\pytorch_fft-0.15.tar.gz
    Complete output from command python setup.py egg_info:
    error in pytorch_fft setup command: 'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-req-build-kpn4v7h5\\build.py:ffi' must be of the form 'path/build.py:ffi_variable'`

**Comment by andrehuang** [comment]
This issue should be raised in the pytorch fft thread.

**Comment by Mrmoore98** [comment]
and I met another problem when I try to run this program  `Traceback (most recent call last):
  File "main.py", line 38, in <module>
    from utils import *
  File "C:\Users\dell\Downloads\LaplacianSmoothing-GradientDescent-master\LaplacianSmoothing-GradientDescent-master\Small-BatchSize\utils.py", line 29, in <module>
    _, term_width = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)`

**Comment by andrehuang** [comment]
The code may not be mature (it actually looks like a pre-published version). But the core function is good to use. Try just use the LS_SGD function along with its class Optimizer. Just import the optimizer and use it like you use SGD in your own model.

**Comment by Mrmoore98** [comment]
thx

**Comment by BaoWangMath** [comment]
@Mrmoore98 The updated code does not rely on external fft.
